"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Added for os.getenv pattern

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'default-insecure-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rag',
    'rest_framework',
    'knox',
    'corsheaders',
    'drf_yasg',  # Add drf-yasg for Swagger
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #CORS MiddleWare
    'corsheaders.middleware.CorsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',
    ],
}

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

AUTH_USER_MODEL = 'rag.User'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'new_test.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "static"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# API Keys Configuration
# ------------------------------------------------------------------------------
# Load API keys from environment variables for security
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')  # Changed from hardcoded empty string

# If no environment variable is set, you can still set it here for development
# OPENAI_API_KEY = 'sk-your-api-key-here'  # Uncomment and add your key for development

# Validate that API key is set
if not OPENAI_API_KEY or OPENAI_API_KEY.strip() == '':
    import warnings
    warnings.warn(
        "OPENAI_API_KEY is not set! Please set it in environment variables or settings.py",
        UserWarning
    )


SECURE_CROSS_ORIGIN_OPENER_POLICY=None

# Value determines whether the server allows cookies in the cross-site HTTP requests
CORS_ALLOW_CREDENTIALS = True

# Methods allowed for CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'OPTIONS',
    'PATCH',
    'GET',
    'POST',
    'PUT',  
]

# Non-standard headers allowed in the request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ORIGIN_WISHLIST = [
    'http://localhost:4200',
    'http://127.0.0.1:5000',
    'http://127.0.0.1:8000'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]

# LLM and Vector Store Configuration
# ------------------------------------------------------------------------------
# Expected dimension for vectors stored in Qdrant.
# Ensure this matches the output dimension of your primary embedding model.
QDRANT_VECTOR_DIMENSION = 1536

# Ollama Configuration
# ------------------------------------------------------------------------------
# Base URL for the Ollama API server.
OLLAMA_API_URL = ""
OLLAMA_BASE_URL = OLLAMA_API_URL
# Default timeout in seconds for requests to the Ollama API.
OLLAMA_REQUEST_TIMEOUT = 300  # 5 minutes, aligns with Ollama's common default

# Default LLM Provider Configuration
# ------------------------------------------------------------------------------
# Specifies the system-wide default LLM provider if no user-specific key is active.
# Options: "OPENAI", "OLLAMA" (add more as other providers are implemented)
DEFAULT_LLM_PROVIDER = "OpenAI"

# Default model names for OpenAI
DEFAULT_OPENAI_MODEL = "gpt-4.1"
DEFAULT_OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"
# Note: OPENAI_API_KEY is defined earlier in this file.
# It should ideally be loaded via os.getenv("OPENAI_API_KEY").

# Default model names for Ollama
DEFAULT_OLLAMA_MODEL = "llama3.1:latest" # Default chat model for Ollama
DEFAULT_OLLAMA_EMBEDDING_MODEL = "bge-m3" # Default embedding model for Ollama
# OLLAMA_API_KEY = os.getenv("OLLAMA_API_KEY") # Define if your Ollama instance uses an API key


DEFAULT_EMBEDDING_PROVIDER = "text-embedding-3-large"  # Default embedding provider if not specified by user
DEFAULT_LLM_PROVIDER = "OpenAI"
DEFAULT_MODEL = "gpt-4.1"  # Default LLM model if not specified by user

QDRANT_HOST = 'localhost'
QDRANT_PORT = '6333'

# Excel/CSV Processing Configuration
# ------------------------------------------------------------------------------
ROWS_PER_CHUNK = 100  # Reduced from 500 for better granularity
EXCEL_MAX_CHUNK_SIZE = 3000  # Larger chunks for Excel data
EXCEL_CHUNK_OVERLAP = 300   # More overlap for context preservation

# Vector Store Configuration for Large Files
# ------------------------------------------------------------------------------
QDRANT_BATCH_SIZE = 50  # Increase batch size for Excel processing
QDRANT_VECTOR_DIMENSION = 1536  # Ensure this matches your embedding model

# Large File Processing Configuration
# ------------------------------------------------------------------------------
LARGE_FILE_THRESHOLD = 50000  # Trigger streaming for files > 50k rows
ROWS_PER_CHUNK = 5000  # Process 5k rows per chunk
EXCEL_MAX_CHUNK_SIZE = 8000  # Larger text chunks for better context
EXCEL_CHUNK_OVERLAP = 800   # More overlap for large datasets
CHUNK_SIZE_LARGE = 5000  # Larger processing chunks

# Vector Store Configuration for Large Files
# ------------------------------------------------------------------------------
QDRANT_BATCH_SIZE = 100  # Larger batch size for efficiency
QDRANT_TIMEOUT = 300  # 5 minute timeout for large operations

# OCR Configuration
# ------------------------------------------------------------------------------
MAX_OCR_WORKERS = 4