# Generated by Django 5.2 on 2025-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_assistant_vector_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='instructions',
            field=models.TextField(blank=True, help_text='Custom instructions for the assistant, used as the system prompt during runs.', null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='run',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
