# Generated by Django 5.2 on 2025-06-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_document_user_documentalert_user_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='model',
            field=models.CharField(default='gpt-4o', help_text='OpenAI model to use with this key', max_length=50),
        ),
        migrations.AddField(
            model_name='openaikey',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for the API key', max_length=255, null=True),
        ),
    ]
