# Generated by Django 5.2 on 2025-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='provider',
            field=models.CharField(choices=[('OpenAI', 'OpenAI'), ('Ollama', 'Ollama'), ('Claude', 'Claude')], default='OpenAI', max_length=50),
        ),
    ]
