# Generated by Django 5.2 on 2025-06-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_openaikey_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaikey',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the key was last deactivated.', null=True),
        ),
        migrations.AddField(
            model_name='openaikey',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this key currently active for the user?'),
        ),
        migrations.AddConstraint(
            model_name='openaikey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='unique_active_key_per_user'),
        ),
    ]
