# Generated by Django 5.2 on 2025-08-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_openaikey_deactivated_at_openaikey_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='model',
            field=models.CharField(default='gpt-4o', help_text='LLM model to use for this assistant.', max_length=100),
        ),
        migrations.AddField(
            model_name='assistant',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text='List of tools (JSON schemas) for the assistant.'),
        ),
        migrations.AddField(
            model_name='run',
            name='required_action',
            field=models.JSONField(blank=True, help_text='Details for required actions like tool calls.', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='tool_outputs',
            field=models.JSONField(blank=True, help_text='Submitted tool outputs for resumption.', null=True),
        ),
    ]
