# Generated by Django 5.2 on 2025-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0010_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated title based on first user message', max_length=255, null=True),
        ),
    ]
