# Generated by Django 5.2 on 2025-09-19 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0011_thread_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="rerun_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the run that this run is rerunning, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reruns",
                to="rag.run",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Original user message that triggered this run, when available.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_runs",
                to="rag.message",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In Progress"),
                    ("requires_action", "Requires Action"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.CharField(
                        choices=[("good", "Good"), ("bad", "Bad")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="rag.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "user")},
            },
        ),
    ]
