# Generated by Django 5.2 on 2025-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0012_run_cancelled_at_run_rerun_of_run_source_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaikey",
            name="chat_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional generation controls to override provider defaults (e.g., temperature, max_tokens).",
            ),
        ),
    ]
