# Generated by Django 5.2 on 2025-12-11 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0013_openaikey_chat_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="model",
            field=models.CharField(
                default="gpt-4.1",
                help_text="LLM model to use for this assistant.",
                max_length=100,
            ),
        ),
        migrations.RenameModel(
            old_name="OpenAIKey",
            new_name="LLMProviderConfig",
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name for the credential or endpoint",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="model",
            field=models.CharField(
                default="gpt-4.1",
                help_text="Preferred chat model to use with this configuration",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Is this configuration currently active for the user?",
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the configuration was last deactivated.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_provider_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
