# Generated by Django 5.2 on 2025-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0014_alter_assistant_model_llmproviderconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderconfig",
            name="base_url",
            field=models.CharField(
                blank=True,
                help_text="Optional base URL for provider requests (e.g., Ollama host).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_setup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="selected_llm_provider",
            field=models.CharField(
                choices=[
                    ("OpenAI", "OpenAI"),
                    ("Ollama", "Ollama"),
                    ("Claude", "Claude"),
                ],
                default="OpenAI",
                help_text="The LLM provider currently selected for this user.",
                max_length=50,
            ),
        ),
    ]
