# Generated by Django 5.2 on 2025-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0015_llmproviderconfig_base_url_user_is_setup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="collection_created",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the tenant collection has been created for this user.",
            ),
        ),
    ]
