# Generated by Django 5.2 on 2026-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0026_alter_conversation_id_responserecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this configuration currently active for the user?",
            ),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="is_valid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("OpenAI", "OpenAI"),
                    ("Ollama", "Ollama"),
                    ("Claude", "Claude"),
                ],
                db_index=True,
                default="OpenAI",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="responserecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In Progress"),
                    ("requires_action", "Requires Action"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="active_collection_ready",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether the active collection has been provisioned for this user.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="llm_configured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether the user has configured an LLM and collection.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="selected_llm_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OpenAI", "OpenAI"),
                    ("Ollama", "Ollama"),
                    ("Claude", "Claude"),
                ],
                db_index=True,
                default=None,
                help_text="The LLM provider currently selected for this user.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="assistant",
            index=models.Index(
                fields=["tenant", "is_default"], name="assistant_tenant_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["tenant", "is_active"], name="collection_tenant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["tenant", "user", "created_at"],
                name="conv_tenant_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="conversation_msg_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmessage",
            index=models.Index(
                fields=["user", "created_at"], name="convmsg_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "user", "uploaded_at"],
                name="doc_tenant_user_upload_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "vector_store"], name="document_tenant_store_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "vector_store"], name="document_user_store_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "uploaded_at"], name="document_status_uploaded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["vector_store", "document"], name="doc_access_store_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentalert",
            index=models.Index(
                fields=["document", "created_at"], name="doc_alert_document_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentalert",
            index=models.Index(
                fields=["user", "created_at"], name="doc_alert_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmproviderconfig",
            index=models.Index(
                fields=["user", "provider"], name="llm_config_user_provider_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmproviderconfig",
            index=models.Index(
                fields=["user", "is_valid", "is_active"],
                name="llm_config_user_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created_at"], name="message_thread_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "created_at"], name="message_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="responserecord",
            index=models.Index(
                fields=["tenant", "user", "created_at"],
                name="resp_tenant_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responserecord",
            index=models.Index(
                fields=["status", "created_at"], name="response_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["thread", "created_at"], name="run_thread_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["status", "created_at"], name="run_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["tenant", "user", "created_at"],
                name="thread_tenant_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vectorstore",
            index=models.Index(
                fields=["tenant", "user", "collection"], name="vs_tenant_user_col_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vectorstore",
            index=models.Index(
                fields=["tenant", "collection"], name="vector_store_tenant_col_idx"
            ),
        ),
    ]
